create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  kind text not null check (kind in ('savings', 'investment')),
  institution text not null default '',
  principal numeric not null default 0 check (principal >= 0),
  current_balance numeric not null default 0 check (current_balance >= 0),
  annual_rate numeric not null default 0 check (annual_rate >= 0),
  updated_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists idx_assets_user_updated on public.assets(user_id, updated_date desc);
alter table public.assets enable row level security;
drop policy if exists "Usuários gerenciam os próprios dados" on public.assets;
create policy "Usuários gerenciam os próprios dados" on public.assets
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
